### ISSUE TITLE
Build or watch multiple folders to single or multiple sprites

### ISSUE THREAD

**Issue by jgarber623** [jgarber623/svgeez#4]
Perhaps passed into `build` and `watch` as `--config` with a path to a YML file?

```yml
- source: /foo/bar
  destination: /foo
- source: /biz/baz
  destination: /biz
```
